### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by embeddedt** [alexdawn/transporter#187]
First of all, impressive project!

I'm curious about how you were planning to license this.

**Comment by alexdawn** [comment]
Hi Embeddet,

Thanks for asking! Im affraid I havent yet decided on a licence, so currently there is no licence (all rights reserved). I guess the really question is what are you hoping to do with this?

While it is still a long way from completion I am hoping to be able to sell the game one day, I believe that will limit the type of licence I can give the project. With that in mind I am considering MIT while reserving rights on the 3D models. Of course I'm open to suggestions and recomendations.
